export const materialsDensity = [
  { id: 1, material: "Stal", density: 7.8 },
  { id: 2, material: "Aluminium", density: 2.7 },
  { id: 3, material: "Beton", density: 2.2 },
  { id: 5, material: "Brąz", density: 8.8 },
  { id: 6, material: "Chrom", density: 7.19 },
  { id: 7, material: "Cyna", density: 7.29 },
  { id: 8, material: "Cynk", density: 7.13 },
  { id: 9, material: "Krzem", density: 2.33 },
  { id: 10, material: "Miedź", density: 8.9 },
  { id: 11, material: "Ołów", density: 11.3 },
  { id: 12, material: "Platyna", density: 21.5 },
  { id: 13, material: "Złoto", density: 19.3 },
  { id: 14, material: "Wolfram", density: 19.2 },
];
